create table user_accounts(

id BIGINT GENERATED BY DEFAULT AS IDENTITY,

email varchar(255) NOT NULL,

password_hash varchar(255) NOT NULL,

role varchar(50) NOT NULL,
status varchar(50) NOT NULL,

email_Verified boolean NOT NULL DEFAULT FALSE,
last_login_at TIMESTAMP WITH TIME ZONE,

created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

version BIGINT NOT NULL DEFAULT 0,

CONSTRAINT pk_user_accounts
    PRIMARY KEY(id),

    CONSTRAINT uk_user_accounts_email
        UNIQUE(email)

)